/* 
 * File:   main.cpp
 * Author: John Olmos
 * Created on January 10, 2018, 12:40 PM
 * Purpose: Calculate income generated by ticket sales
 */

//System Libraries
#include <iostream>
#include <iomanip>
using namespace std;

//User Libraries

//Global Constants - Math/Physics Constants, Conversions,
//                   2-D Array Dimensions

//Function Prototypes

//Execution Begins Here
int main(int argc, char** argv) {
    //Declare Variables
    int aTS,bTS,cTS;//Number of A, B, and C class tickets sold
    float inc;//Total income generated from ticket sales in USD
    
    //Initialize Variables   
    cout<<"Enter the number A class seat tickets sold: ";
    cin>>aTS;//Total number of $15 Class A seats sold
    cout<<"Enter the number B class seat tickets sold: ";
    cin>>bTS;//Total number of $12 Class B seats sold
    cout<<"Enter the number C class seat tickets sold: ";
    cin>>cTS;//Total number of $9 Class C seats sold    
    
    //Process/Map inputs to outputs
    inc=aTS*15+bTS*12+cTS*9;/*Multiply each ticket type by 
                              their respective cost in USD.*/
    
    //Output data
    cout<<fixed<<setprecision(2)<<showpoint
        <<"Total income generated from ticket sales = $"<<inc<<endl;
    
    //Exit stage right!
    return 0;
}